"""refactor

Revision ID: 0d317f1c7598
Revises: 5435ea408a6c
Create Date: 2023-03-02 21:28:36.700852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d317f1c7598'
down_revision = '5435ea408a6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courseteacher', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('studentassessment', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('studentcourse', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentcourse', 'id')
    op.drop_column('studentassessment', 'id')
    op.drop_column('courseteacher', 'id')
    # ### end Alembic commands ###
