"""init edit

Revision ID: 4d4cd92899cb
Revises: e4c576578c79
Create Date: 2023-03-02 19:00:58.727887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4cd92899cb'
down_revision = 'e4c576578c79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
