"""correction fixed new

Revision ID: 5435ea408a6c
Revises: a7466fda6d7c
Create Date: 2023-03-02 21:12:41.846744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5435ea408a6c'
down_revision = 'a7466fda6d7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
