"""correction new

Revision ID: 93ff00be0dbf
Revises: a9e1e3ae6ca5
Create Date: 2023-03-02 21:06:56.907723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ff00be0dbf'
down_revision = 'a9e1e3ae6ca5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
