"""correction

Revision ID: a9e1e3ae6ca5
Revises: e85d63a99eed
Create Date: 2023-03-02 19:32:43.710289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e1e3ae6ca5'
down_revision = 'e85d63a99eed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
