"""init another

Revision ID: ad33e7146b78
Revises: 4d4cd92899cb
Create Date: 2023-03-02 19:06:48.484840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad33e7146b78'
down_revision = '4d4cd92899cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
