"""new field

Revision ID: e85d63a99eed
Revises: ad33e7146b78
Create Date: 2023-03-02 19:17:50.064730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85d63a99eed'
down_revision = 'ad33e7146b78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
